name 'my_cookbook'
maintainer 'saikeerthi'
maintainer_email 'saikeerthi@gmail.com'
license 'All Rights Reserved'
description 'Installs/Configures my_cookbook'
long_description 'Installs/Configures my_cookbook'
version '0.1.0'
chef_version '>= 15.0'
